### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by guit4eva** [obitoo/PebbleTidesUK#12]
The server went down today - a huge sadness!! Is there any chance that it will be back up again, or if I can possibly host it somehow to continue the Tides watch face legacy?

**Comment by obitoo** [comment]
Just a blip after an automated reboot, sorry!    Should be working fine now
- let me know if issues still.

Glad to know someone apart from me still using and enjoying it ;)

Cheers,
Owen

**Comment by guit4eva** [comment]
Hi there Owen,

Apologies for the late reply, your reply slipped into the depths of my overcrowded inbox! I was so stoked to see it back up and running - I rely on it daily! It's almost the main reason I actually wear my pebble :) I'm sure a lot of other people are also using it, as it's really a great watchface! 

If you ever decide to update it in future, one suggestion would be to make the bluetooth connect/disconnect vibration optional :) But otherwise it's perfect!

Thanks for making one of the most useful watchfaces available! Keep safe during this crazy Corona time!

Regards from South Africa,
Rudi
